# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/squeakily',
                'doc_host': 'https://CarperAI.github.io',
                'git_url': 'https://github.com/CarperAI/squeakily',
                'lib_path': 'squeakily'},
  'syms': {'squeakily.core': {'squeakily.core.foo': ('core.html#foo', 'squeakily/core.py')}}}