# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/squeakily',
                'doc_host': 'https://CarperAI.github.io',
                'git_url': 'https://github.com/CarperAI/squeakily',
                'lib_path': 'squeakily'},
  'syms': { 'squeakily.clean': { 'squeakily.clean.normalize_whitespace': ('clean.html#normalize_whitespace', 'squeakily/clean.py'),
                                 'squeakily.clean.remove_empty_lines': ('clean.html#remove_empty_lines', 'squeakily/clean.py')},
            'squeakily.core': { 'squeakily.core.Pipeline': ('core.html#pipeline', 'squeakily/core.py'),
                                'squeakily.core.Pipeline.__init__': ('core.html#pipeline.__init__', 'squeakily/core.py'),
                                'squeakily.core.Pipeline.run': ('core.html#pipeline.run', 'squeakily/core.py')},
            'squeakily.filter': { 'squeakily.filter._char_rep_ratio': ('filter.html#_char_rep_ratio', 'squeakily/filter.py'),
                                  'squeakily.filter._flag_word_ratio': ('filter.html#_flag_word_ratio', 'squeakily/filter.py'),
                                  'squeakily.filter.check_char_repetition': ('filter.html#check_char_repetition', 'squeakily/filter.py'),
                                  'squeakily.filter.check_exact_match': ('filter.html#check_exact_match', 'squeakily/filter.py'),
                                  'squeakily.filter.check_flagged_words': ('filter.html#check_flagged_words', 'squeakily/filter.py')},
            'squeakily.helpers': {'squeakily.helpers.get_words': ('helpers.html#get_words', 'squeakily/helpers.py')}}}